import { html, LitElement } from "lit";
import './App.less';
//New Components
import { MenuLinks } from "../MenuLinks/MenuLinks";
import { Card } from "../Card/Card";
//Images
import profilImage from '../../images/avatar.png';
//Data
import { generateCard } from "../../data/data_card";

export class App extends LitElement {
    static properties = {
        isOpen:{type:Boolean},
        cards:{type:Array},
        filteredCards:{type:Array},
        searchData:{type:String}
    }

    constructor(){
        super();
        this.isOpen = false;
        this.cards = [];
        this.filteredCards = [];
        this.searchData = "";
    }

    toggleMenuMobile() {
        if(document.body.classList.contains('menumobile')){
            document.body.classList.remove('menumobile');
            this.isOpen = false;
        }else {
            document.body.classList.add('menumobile');
            this.isOpen = true;
        }

        this.dispatchEvent(new CustomEvent('menu-toggle', {
            detail: { open: this.isOpen },
            bubbles: true,
            composed: true
        }));
    }

    filterCards(){
        //Filter card by the name -> if we have something in the input we filter if not we show the 10 by default
        if(this.searchData){
            this.filteredCards = this.cards.filter(card =>
                card.name.toLowerCase().includes(this.searchData.toLowerCase())
            )
        }else {
            this.filteredCards = [...this.cards];
        }
    }

    handleSearchData(event) {
        this.searchData = event.target.value;  // Update the search data value
        this.filterCards();  //Filter cards
    }

    showCard(){
        this.cards = Array.from({ length: 10 }, () => generateCard()); // Cards generated by default
        this.filteredCards = [...this.cards]; 
    }

    createRenderRoot() {
        return this; //Allow the outside styles affect the component
    }

    addCard(){
        const newCard = generateCard();
        this.filteredCards = [...this.filteredCards, newCard];
        this.cards = [...this.cards, newCard]; //Update the base array complete
    }

    connectedCallback() {
        super.connectedCallback();
        this.showCard(); // Create and show the card when the component is already mounted
    }

    render(){
        return html `
            <header class="geo_header" role="banner">
                <div class="geo_nav_menu">
                    <div class="geo_nav_menu_tabs">
                        <a class="geo_nav_menu_tabs_item" title="Homepage" href="#">
                            <span class="geo_home_icon" aria-hidden="true"></span>
                        </a>
                    </div>

                    <nav role="navigation" aria-label="Principal Menu" class="geo_nav_menu_links">
                        <button type="button" aria-expanded="false" class="geo_burger_btn" @click="${this.toggleMenuMobile}">
                            <span class="geo_burger_btn_container" aria-hidden="true">
                                <span class="geo_burger_btn_lines"></span>
                            </span>
                        </button>
                        <div class="geo_nav_menu_links_container">
                            <ul class="geo_nav_menu_items">
                                <li>
                                    <menu-link title="Go to favorites page" iconClass="geo_star_icon" text="Favorites"></menu-link>                                    
                                </li>
                                <li>
                                    <menu-link title="Go to setting page" iconClass="geo_settings_icon" text="Configuration"></menu-link>
                                </li>
                                <li>
                                    <menu-link title="Go to help page" iconClass="geo_suppport_icon" text="Help Page"></menu-link>
                                </li>
                                <li>
                                    <menu-link title="Go to see your messages" iconClass="geo_mail_icon" notification="4" text="Messages"></menu-link>
                                </li>
                                <li>
                                <menu-link title="Go to notifications page" iconClass="geo_notification_icon" .separator="${false}" text="Notification"></menu-link>
                                </li>
                            </ul>
                            <div class="geo_authen_container">
                                ${this.isOpen
                                    ? html`
                                        <img src="${profilImage}" alt="Profil Photo" width="40" height="40"/>
                                        <a href="#" title="Sign Out" class="geo_authen_container_link">Sign out</a>`
                                    : html`
                                        <a href="#" title="Show Profil Options">
                                            <img src="${profilImage}" alt="Profil Photo" width="40" height="40"/>
                                        </a>`
                                }
                            </div>
                        </div>
                    </nav>
                </div>

                <div class="geo_header_content">
                    <div class="geo_header_add">
                        <span>Créer</span>
                        <button role="button" title="Créer une nouvelle carte" @click="${this.addCard}">
                            <span aria-hidden="true" class="geo_add_icon"></span>
                        </button>
                    </div>

                    <div role="search" class="geo_search">
                       <label class="geo_search_label">Rechercher</label>
                       <div>
                            <input type="text" title="Votre recherche d'une ressource" placeholder="Nom d'une ressource" .value="${this.searchData}" @input="${this.handleSearchData}">
                            <button type="button" class="geo_search_btn">
                                <span class="invisible">Lancer la recherche</span>
                                <span aria-hidden="true" class="geo_search_icon"></span>
                            </button>
                       </div>
                       
                    </div>
                </div>

                <div class="geo_header_tools"></div>
            </header>

            <main role="main">
                <div class="geo_main_container">
                    ${this.filteredCards.map(card => html`
                        <card-map .card="${card}"></card-map>
                    `)}
                </div>
            </main>
        `
    }
}

customElements.define('app-root', App);